# Generated by Django 4.1 on 2022-08-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=128)),
                ('hobbys', models.CharField(max_length=128)),
                ('proyecto_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_familiares.datos')),
            ],
        ),
    ]
