# Generated by Django 4.1 on 2022-08-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesante',
            name='proyecto_familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_familiares.datos'),
        ),
    ]
